name: build
on:
  push: []
  schedule:
  - cron: 59 14 * * *
  pull_request: []

jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-11, windows-2022]
        ghc-version:
        - "8.8"
        - "8.10"
        - "9.0"
    env:
      STACK_YAML: stack-ghc-${{ matrix.ghc-version }}.yaml
    steps:
    - uses: actions/checkout@v2
    - uses: dahlia/actions/setup-yq@main
    - name: Cache Stack files (non-Windows)
      if: "!startsWith(matrix.os, 'windows-')"
      uses: actions/cache@v2
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          ~/.stack
        key: stack-${{ matrix.os }}-ghc-${{ matrix.ghc-version }}
    - name: Cache Stack files (Windows)
      if: "startsWith(matrix.os, 'windows-')"
      uses: actions/cache@v2
      with:
        path: |
          %APPDATA%\cabal\packages
          %APPDATA%\cabal\store
          %APPDATA%\stack
        key: stack-${{ matrix.os }}-ghc-${{ matrix.version }}
    - name: Adjust Stack configuration
      if: "startsWith(matrix.os, 'windows-')"
      run: >-
        yq eval
        -i
        '.flags.seonbi.iconv = false'
        stack-ghc-${{ matrix.ghc-version }}.yaml
    - name: Set up resolver
      shell: bash
      run: |
        # Try 3 times because this sometimes fails due to network error
        # on GitHub Actions.
        stack setup || stack setup || stack setup
    - name: Check version
      if: >-
        github.event_name != 'pull_request' &&
        startsWith(github.ref, 'refs/tags/')
      shell: bash
      run: |
        pkg_ver="$(stack query locals seonbi version)"
        echo "Package version: $pkg_ver"
        tag_ver="${GITHUB_REF:10}"
        echo "Git tag version: $tag_ver"
        [[ "$tag_ver" = "$pkg_ver" ]]
        ! grep -i "to be released" CHANGES.md
    - name: Resolve dependencies
      run: stack install --test --only-dependencies
    - name: Build
      run: stack build --test
    - name: Test
      run: stack test
    - name: Package source distribution
      if: startsWith(matrix.os, 'ubuntu-')
      run: |
        # Hackage disallows -Werror
        sed -i 's/^ *- -Werror$//g' package.yaml
        stack sdist --ignore-check || true
        mkdir -p /tmp/sdist
        mv "$(stack path --dist-dir)"/*.tar.gz /tmp/sdist/
        ls -al /tmp/sdist
    - name: Save source distribution
      if: startsWith(matrix.os, 'ubuntu-')
      uses: actions/upload-artifact@v2
      with:
        name: sdist-${{ matrix.os }}-ghc-${{ matrix.ghc-version }}
        path: /tmp/sdist
    - name: Build docs
      if: >-
        startsWith(matrix.os, 'ubuntu-') &&
        matrix.ghc-version == '8.8'
      shell: bash
      run: |
        curl -L -o /tmp/pandoc.deb \
          https://github.com/jgm/pandoc/releases/download/2.14.2/pandoc-2.14.2-1-amd64.deb
        sudo dpkg -i /tmp/pandoc.deb
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64
        sudo add-apt-repository ppa:rmescandon/yq
        sudo apt update
        sudo apt-get install -y yq
        bash scripts/haddock-prologue/build.sh
    - name: Copy docs
      if: >-
        startsWith(matrix.os, 'ubuntu-') &&
        matrix.ghc-version == '8.8'
      shell: bash
      run: cp -r "$(stack path --dist-dir)/doc/html/seonbi" .docs
    - name: Save docs
      if: >-
        startsWith(matrix.os, 'ubuntu-') &&
        matrix.ghc-version == '8.8'
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: .docs
    - name: Build using -fembed-dictionary
      run: stack build --flag seonbi:embed-dictionary
    - name: Copy executable binaries
      shell: bash
      run: cp -r "$(stack path --local-install-root)/bin" .bin
    - name: Compress executable binaries
      if: "startsWith(matrix.os, 'ubuntu-')"
      uses: crazy-max/ghaction-upx@v1
      with:
        files: .bin/seonbi*
        args: "-9"
    - name: Save executable binaries
      uses: actions/upload-artifact@v2
      with:
        name: binaries-${{ matrix.os }}-ghc-${{ matrix.ghc-version }}
        path: .bin

  deno:
    name: Deno client library
    needs:
    - build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-11, windows-2022]
    steps:
    - uses: actions/checkout@v2
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - uses: actions/download-artifact@v4.1.7
      with:
        name: binaries-${{ matrix.os }}-ghc-8.8
        path: ${{ runner.temp }}/bin
    - run: chmod +x ${{ runner.temp }}/bin/*
      if: "!startsWith(matrix.os, 'windows-')"
    - working-directory: scripts/deno/
      env:
        SEONBI_API: >-
          ${{ runner.temp }}/bin/seonbi-api${{
            startsWith(matrix.os, 'windows-') && '.exe' || ''
          }}
      run: '"$SEONBI_API" --help'
      if: "!startsWith(matrix.os, 'windows-')"
    - working-directory: scripts/deno/
      env:
        SEONBI_API: >-
          ${{ runner.temp }}/bin/seonbi-api${{
            startsWith(matrix.os, 'windows-') && '.exe' || ''
          }}
      shell: cmd
      run: '%SEONBI_API% --help'
      if: "startsWith(matrix.os, 'windows-')"
    - name: Test (manual install)
      working-directory: scripts/deno/
      env:
        SEONBI_API: >-
          ${{ runner.temp }}/bin/seonbi-api${{
            startsWith(matrix.os, 'windows-') && '.exe' || ''
          }}
        SEONBI_API_PORT: ${{ startsWith(matrix.os, 'macos-') && 8800 || 3800 }}
        DENO_JOBS: 1
      run: >-
        deno test
        --check
        --allow-env=SEONBI_API,SEONBI_API_PORT,SEONBI_API_URL
        --allow-net=127.0.0.1:${{ env.SEONBI_API_PORT }}
        --allow-run
        --unstable
    - name: Test (auto install)
      working-directory: scripts/deno/
      env:
        SEONBI_API_PORT: ${{ startsWith(matrix.os, 'macos-') && 8800 || 3800 }}
        DENO_JOBS: 1
      run: >-
        deno test
        --check
        --allow-env=SEONBI_API,SEONBI_API_PORT,SEONBI_API_URL,TMPDIR,TEMP
        --allow-read
        --allow-write
        --allow-net=127.0.0.1:${{ env.SEONBI_API_PORT }},github.com,github-releases.githubusercontent.com,dahlia.github.io,hongminhee.org
        --allow-run
        --unstable
    - name: Test (hosted server)
      working-directory: scripts/deno/
      env:
        SEONBI_API_URL: https://seonbi.fly.dev/
        SEONBI_API: >-
          ${{ runner.temp }}/bin/seonbi-api${{
            startsWith(matrix.os, 'windows-') && '.exe' || ''
          }}
        SEONBI_API_PORT: ${{ startsWith(matrix.os, 'macos-') && 8800 || 3800 }}
        DENO_JOBS: 1
      run: >-
        deno test
        --check
        --allow-env=SEONBI_API,SEONBI_API_PORT
        --allow-net=seonbi.fly.dev,127.0.0.1:${{ env.SEONBI_API_PORT }}
        --allow-run
        --unstable

  image:
    name: Docker image
    outputs:
      image: ${{ steps.push-image.outputs.image }}
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - id: push-image
      run: |
        image_name="dahlia/seonbi"
        gh_image_name="docker.pkg.github.com/$GITHUB_REPOSITORY/bin"
        declare -a build_opts=()
        if [[ "$GITHUB_EVENT_NAME" = "pull_request" ]]; then
          sha="$(git log -n1 --format=%h)"
          tag="git-$sha"
        else
          if [[ "$GITHUB_REF" = "refs/heads/main" ]]; then
            tag=latest
          elif [[ "$GITHUB_REF" = refs/tags/* ]]; then
            tag="${GITHUB_REF:10}"
            build_opts+=(--label "org.opencontainers.image.version=$tag")
          else
            tag="${GITHUB_REF:11}"
          fi
        fi
        docker build \
          --tag "$image_name:$tag" \
          --tag "$gh_image_name:$tag" \
          --label org.opencontainers.image.revision=`git log -1 --format=%H` \
          --label \
            org.opencontainers.image.url=https://github.com/$GITHUB_REPOSITORY \
          --label org.opencontainers.image.description="$(cat README.md)" \
          "${build_opts[@]}" \
          .
        if [[ "$GITHUB_EVENT_NAME" != "pull_request" ]]; then
          docker login \
            docker.pkg.github.com \
            --username "${GITHUB_REPOSITORY#*/}" \
            --password "${{ secrets.GH_TOKEN }}"
          docker login \
            --username "${image_name%/*}" \
            --password "${{ secrets.DOCKERHUB_TOKEN }}"
          docker push "$gh_image_name:$tag"
          docker push "$image_name:$tag"
          echo "::set-output name=image::$gh_image_name:$tag"
        fi
        docker save -o /tmp/image.tar "$image_name:$tag"
        mkdir -p /tmp/images
        pushd /tmp/images
        tar xvf /tmp/image.tar
        popd
        mkdir -p /tmp/image-metadata
        docker images "$image_name:$tag" | tail -n 1 | awk '{print $3}' \
          > /tmp/image-metadata/image_id.txt
    - uses: actions/upload-artifact@v2
      with:
        name: image
        path: /tmp/images
    - uses: actions/upload-artifact@v2
      with:
        name: image-metadata
        path: /tmp/image-metadata

  fly:
    name: Deploy seonbi-api to Fly.io
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs:
    - image
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      IMAGE: ${{ needs.image.outputs.image }}
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - run: |
        curl -L -o /tmp/subtoml \
          https://github.com/pbzweihander/subtoml-rs/releases/download/v0.1.0/subtoml
        chmod +x /tmp/subtoml
        /tmp/subtoml \
          -i fly.toml \
          -o fly.toml \
          build.image="$IMAGE"
        cat fly.toml
    - run: flyctl deploy --remote-only

  binaries:
    name: Package executable binaries
    needs:
    - build
    - image
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v4.1.7
      with:
        name: binaries-macos-11-ghc-8.8
        path: /tmp/binaries-macos
    - uses: actions/download-artifact@v4.1.7
      with:
        name: binaries-windows-2022-ghc-8.8
        path: /tmp/binaries-windows
    - uses: actions/download-artifact@v4.1.7
      with:
        name: image
        path: /tmp/images
    - uses: actions/download-artifact@v4.1.7
      with:
        name: image-metadata
        path: /tmp/image-metadata
    - run: |
        workspace="${{ github.workspace }}"
        mkdir -p /tmp/dists
        # Linux
        pushd /tmp/images
        tar cvf ../image.tar .
        popd
        docker load -i /tmp/image.tar
        mkdir -p /tmp/binaries-linux
        image_id="$(cat /tmp/image-metadata/image_id.txt)"
        docker run -i "$image_id" cat /usr/local/bin/seonbi \
          > /tmp/binaries-linux/seonbi
        docker run -i "$image_id" cat /usr/local/bin/seonbi-api \
          > /tmp/binaries-linux/seonbi-api
        pushd /tmp/binaries-linux
        chmod +x *
        cp "$workspace/"{LICENSE,README.md,CHANGES.md} ./
        tar cvfj /tmp/dists/seonbi.linux-x86_64.tar.bz2 *
        popd
        # macOS
        pushd /tmp/binaries-macos
        chmod +x *
        cp "$workspace/"{LICENSE,README.md,CHANGES.md} ./
        tar cvfj /tmp/dists/seonbi.macos-x86_64.tar.bz2 *
        popd
        # Windows
        pushd /tmp/binaries-windows
        cp "$workspace/"{LICENSE,README.md,CHANGES.md} ./
        zip /tmp/dists/seonbi.win64.zip *
        popd
    - uses: actions/upload-artifact@v2
      with:
        name: dists
        path: /tmp/dists

  release:
    name: Release dist files
    needs:
    - build
    - binaries
    if: >-
      github.event_name != 'pull_request' &&
      startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v4.1.7
      with:
        name: sdist-ubuntu-22.04-ghc-8.8
        path: /tmp/sdist
    - uses: actions/download-artifact@v4.1.7
      with:
        name: dists
        path: /tmp/dists
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir -p "$HOME/bin"
        export PATH="$HOME/bin:$PATH"
        curl -L -o "$HOME/bin/submark" \
          https://github.com/dahlia/submark/releases/download/0.2.0/submark-linux-x86_64
        chmod +x "$HOME/bin/submark"
        curl -L -o $HOME/bin/github-release.bz2 \
          https://github.com/github-release/github-release/releases/download/v0.10.0/linux-amd64-github-release.bz2
        bzip2 -d $HOME/bin/github-release.bz2
        chmod +x $HOME/bin/github-release

        version="${GITHUB_REF:10}"
        github_user="${GITHUB_REPOSITORY%/*}"
        github_repo="${GITHUB_REPOSITORY#*/}"

        # Release note
        submark -iO --h2 "Version $version" CHANGES.md \
        | github-release release \
            --user "$github_user" \
            --repo "$github_repo" \
            --tag "$version" \
            --name "Seonbi $version" \
            --description -

        # Source distribution
        for file in /tmp/sdist/*; do
          github-release upload \
            --user "$github_user" \
            --repo "$github_repo" \
            --tag "$version" \
            --name "$(basename "$file")" \
            --file "$file"
        done

        # Binaries
        for file in /tmp/dists/*; do
          name="$(basename "$file")"
          github-release upload \
            --user "$github_user" \
            --repo "$github_repo" \
            --tag "$version" \
            --name "${name/seonbi/seonbi-$version}" \
            --file "$file"
        done
    - env:
        HACKAGE_API_KEY: ${{ secrets.HACKAGE_API_KEY }}
      run: |
        for file in /tmp/sdist/*; do
          curl \
            -H "Authorization: X-ApiKey $HACKAGE_API_KEY" \
            -F package=@"$file" \
            https://hackage.haskell.org/packages/
        done

  demo:
    name: Deploy demo app
    needs:
    - binaries
    if: >-
      github.event_name != 'pull_request' &&
      github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v4.1.7
      with:
        name: dists
        path: /tmp/dists
    - uses: actions/download-artifact@v4.1.7
      with:
        name: docs
        path: /tmp/docs
    # Generates a showcase SVG image
    - run: |
        mkdir "$HOME/bin/"
        pushd "$HOME/bin/"
        tar xvfj /tmp/dists/seonbi.linux-x86_64.tar.bz2
        popd
        sudo apt-get install -y xqilla
        pushd scripts/showcase-svg/
        make build/showcase.svg SEONBI="$HOME/bin/seonbi"
        popd
    - run: |
        pushd /tmp
        curl -L -o elm.gz \
          https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz
        gunzip elm.gz
        chmod +x elm
        popd
        git config --global user.name "$GITHUB_ACTOR"
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git init /tmp/html
        pushd demo/
        /tmp/elm make --optimize --output=/tmp/html/index.html src/Demo.elm

        # GitHub Corners <https://github.com/tholman/github-corners>
        sed -Ezi 's|\s*</body>\s*</html>\s*$||' /tmp/html/index.html
        {
          cat github-corner.html
          echo '</body></html>'
        } >> /tmp/html/index.html
        popd

        # Showcase SVG
        cp scripts/showcase-svg/build/showcase.svg /tmp/html/

        # Deno client library
        mkdir /tmp/html/deno
        rm -rf /tmp/html/deno/latest
        cp -r scripts/deno /tmp/html/deno/latest
        if [[ "$GITHUB_REF" = refs/tags/* ]]; then
          rmf -rf /tmp/html/deno/"${GITHUB_REF:10}"
          cp -r scripts/deno /tmp/html/deno/"${GITHUB_REF:10}"
        fi
        pushd /tmp/html
        git add deno
        popd

        # Docs
        cp -r /tmp/docs /tmp/html/docs

        cd /tmp/html
        git add index.html
        git add showcase.svg
        git add docs/

        # Bleeding-edge binaries
        mkdir dists
        mv /tmp/dists dists/latest
        git add dists

        git commit -m 'Demo app and docs'
        git branch --move gh-pages
        auth="$GITHUB_ACTOR:${{ secrets.GH_TOKEN }}"
        git remote add origin \
          "https://$auth@github.com/$GITHUB_REPOSITORY.git"
        git push -f origin gh-pages
